# Generated by Django 5.2.1 on 2025-05-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CybersecurityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-shield-alt)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cybersecurity/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display this service')),
            ],
            options={
                'verbose_name': 'Cybersecurity Service',
                'verbose_name_plural': 'Cybersecurity Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CybersecurityTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cybersecurity Testimonial',
                'verbose_name_plural': 'Cybersecurity Testimonials',
            },
        ),
        migrations.CreateModel(
            name='CybersecurityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-lock)', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cybersecurity.cybersecurityservice')),
            ],
            options={
                'verbose_name': 'Cybersecurity Feature',
                'verbose_name_plural': 'Cybersecurity Features',
            },
        ),
    ]
