# Generated by Django 5.2.1 on 2025-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='service_type',
            field=models.CharField(choices=[('education', 'ICT Education'), ('development', 'Software Development'), ('cybersecurity', 'Cybersecurity'), ('computer', 'Computer Sales'), ('network', 'Network Services'), ('general', 'General Inquiry')], max_length=20),
        ),
    ]
