# Generated by Django 5.2.1 on 2025-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_hero', 'Home Hero'), ('about_hero', 'About Hero'), ('education_hero', 'Education Hero'), ('development_hero', 'Development Hero'), ('portfolio_hero', 'Portfolio Hero'), ('contact_hero', 'Contact Hero')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Empowering Through Technology', max_length=100)),
                ('hero_subtitle', models.TextField(default='We provide quality ICT education for all ages and professional software development services tailored to your business needs.')),
                ('services_title', models.CharField(default='Our Services', max_length=100)),
                ('services_subtitle', models.TextField(default='Discover how we can help you or your organization thrive in the digital world')),
                ('education_title', models.CharField(default='ICT Education Services', max_length=100)),
                ('education_subtitle', models.TextField(default='Practical technology education for all ages')),
                ('development_title', models.CharField(default='Software Development Services', max_length=100)),
                ('development_subtitle', models.TextField(default='Custom solutions tailored to your business needs')),
                ('portfolio_title', models.CharField(default='Our Portfolio', max_length=100)),
                ('portfolio_subtitle', models.TextField(default='Check out some of our recent projects')),
                ('testimonial_title', models.CharField(default='What Our Clients Say', max_length=100)),
                ('testimonial_subtitle', models.TextField(default='Testimonials from our satisfied clients')),
                ('cta_title', models.CharField(default='Ready to Transform Your Digital Experience?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Contact us today to discuss your ICT education or software development needs. Our team is ready to help you achieve your goals.')),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ricas IT Services', max_length=100)),
                ('site_logo', models.ImageField(help_text='Site logo displayed in the navbar', upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site/')),
                ('email', models.EmailField(default='services.ricas@gmail.com', max_length=254)),
                ('phone', models.CharField(default='0505584553', max_length=20)),
                ('address', models.CharField(default='Accra, Ghana', max_length=255)),
                ('business_hours', models.CharField(default='Mon-Fri: 9:00 AM - 5:00 PM', max_length=255)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(default='Providing quality ICT education and professional software development services to help individuals and businesses thrive in the digital world.')),
                ('copyright_text', models.CharField(default='© {year} Ricas IT Services. All rights reserved.', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Description for search engines', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Keywords for search engines', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
