# Generated by Django 5.2.1 on 2025-05-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_bannerimage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='section',
            field=models.CharField(choices=[('home_hero', 'Home Hero'), ('about_hero', 'About Hero'), ('education_hero', 'Education Hero'), ('development_hero', 'Development Hero'), ('portfolio_hero', 'Portfolio Hero'), ('contact_hero', 'Contact Hero'), ('cta_image', 'Call to Action Image'), ('about_company', 'About Company Image'), ('education_overview', 'Education Overview Image'), ('development_overview', 'Development Overview Image'), ('about_cta', 'About CTA Image'), ('education_cta', 'Education CTA Image'), ('development_cta', 'Development CTA Image'), ('portfolio_cta', 'Portfolio CTA Image'), ('contact_cta', 'Contact CTA Image')], max_length=50, unique=True),
        ),
    ]
