# Generated by Django 5.2.1 on 2025-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_bannerimage_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ecommerce_url',
            field=models.URLField(blank=True, help_text='URL to the e-commerce website for computer sales', null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='section',
            field=models.CharField(choices=[('home_hero', 'Home Hero'), ('about_hero', 'About Hero'), ('education_hero', 'Education Hero'), ('development_hero', 'Development Hero'), ('portfolio_hero', 'Portfolio Hero'), ('contact_hero', 'Contact Hero'), ('cybersecurity_hero', 'Cybersecurity Hero'), ('computers_hero', 'Computers Hero'), ('network_hero', 'Network Services Hero'), ('cta_image', 'Call to Action Image'), ('about_company', 'About Company Image'), ('education_overview', 'Education Overview Image'), ('development_overview', 'Development Overview Image'), ('cybersecurity_overview', 'Cybersecurity Overview Image'), ('computers_overview', 'Computers Overview Image'), ('about_cta', 'About CTA Image'), ('education_cta', 'Education CTA Image'), ('development_cta', 'Development CTA Image'), ('portfolio_cta', 'Portfolio CTA Image'), ('contact_cta', 'Contact CTA Image'), ('cybersecurity_cta', 'Cybersecurity CTA Image'), ('computers_cta', 'Computers CTA Image')], max_length=50, unique=True),
        ),
    ]
