# Generated by Django 5.2.1 on 2025-05-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='computer_categories/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display this category')),
            ],
            options={
                'verbose_name': 'Computer Category',
                'verbose_name_plural': 'Computer Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NetworkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-network-wired)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='network_services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display this service')),
            ],
            options={
                'verbose_name': 'Network Service',
                'verbose_name_plural': 'Network Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComputerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='computer_products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display this product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='computers.computercategory')),
            ],
            options={
                'verbose_name': 'Computer Product',
                'verbose_name_plural': 'Computer Products',
                'ordering': ['order'],
            },
        ),
    ]
