# Generated by Django 5.2.1 on 2025-05-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('kids', 'Kids (6-12)'), ('teens', 'Teens (13-17)'), ('adults', 'Adults (18+)'), ('all', 'All Ages')], max_length=20)),
                ('learning_goals', models.TextField()),
                ('format', models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20)),
                ('image', models.ImageField(upload_to='education/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
