# Generated by Django 5.2.1 on 2025-05-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('desktop', 'Desktop Application'), ('game', 'Game Development'), ('education', 'Educational Project'), ('other', 'Other')], max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-completion_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
